export function handleTgAdminPage(): Response {
  return new Response(`<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Command Ledger</title><style>
@import url('https://fonts.googleapis.com/css2?family=Noto+Serif+SC:wght@400;500;600;700&display=swap');
:root{--paper:#fbfaf7;--ink:#171613;--muted:#77736d;--line:#d9d5cf;--accent:#cc7d5e;--soft:#f3eee8;--ok:#557263;--warn:#9a684f}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font-family:"Anthropic Serif","Noto Serif SC",Georgia,serif;letter-spacing:0}button,input,select{font:inherit}.shell{min-height:100vh;display:grid;grid-template-columns:190px minmax(0,1fr) 270px}.rail{padding:30px 22px;border-right:1px solid var(--line);position:sticky;top:0;height:100vh}.right{border-right:0;border-left:1px solid var(--line)}.brand{font-size:13px;color:var(--accent);font-weight:700;text-transform:uppercase;margin-bottom:30px}.nav{display:grid;gap:6px}.nav button{border:0;background:transparent;padding:10px 8px;text-align:left;cursor:pointer;color:var(--muted)}.nav button.active{color:var(--ink);border-left:2px solid var(--accent)}main{padding:34px 38px;min-width:0}header{display:flex;align-items:end;justify-content:space-between;border-bottom:1px solid var(--line);padding-bottom:20px;margin-bottom:26px}h1{font-size:38px;font-weight:500;margin:0}h2{font-size:19px;font-weight:600;margin:0 0 16px}.meta{color:var(--muted);font-size:12px}.lanes{display:grid;grid-template-columns:repeat(4,minmax(145px,1fr));gap:12px}.lane{border-top:2px solid var(--ink);padding-top:14px;min-height:290px}.lane h3{font-size:15px;margin:0 0 18px}.count{font-size:42px;color:var(--accent);line-height:1}.note{margin-top:24px;padding:14px 0;border-top:1px solid var(--line);color:var(--muted);font-size:13px;line-height:1.7}.panel{display:none}.panel.active{display:block}.rows{border-top:1px solid var(--line)}.row{display:flex;gap:18px;align-items:center;justify-content:space-between;padding:16px 0;border-bottom:1px solid var(--line)}.row p{margin:4px 0 0;color:var(--muted);font-size:13px}.action{border:1px solid var(--ink);background:transparent;padding:8px 12px;cursor:pointer}.action.primary{background:var(--ink);color:var(--paper)}.action.danger{border-color:var(--accent);color:#923f2f}.links{display:grid;gap:0}.link{display:block;color:var(--ink);text-decoration:none;padding:15px 0;border-bottom:1px solid var(--line)}.link strong{display:block;font-size:14px}.link span{display:block;color:var(--muted);font-size:11px;margin-top:4px}.status{display:inline-block;width:8px;height:8px;border-radius:50%;background:var(--ok);margin-right:8px}.status.off{background:var(--accent)}select{border:1px solid var(--line);background:var(--paper);padding:9px}.empty{color:var(--muted);padding:22px 0}.toast{position:fixed;left:50%;bottom:24px;transform:translateX(-50%);background:var(--ink);color:var(--paper);padding:10px 14px;display:none;font-size:13px}
details{border-bottom:1px solid var(--line);padding:14px 0}summary{cursor:pointer;font-weight:600}.metrics{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px 24px;padding:14px 0}.metric{display:flex;justify-content:space-between;gap:14px;color:var(--muted);font-size:13px}.metric strong{color:var(--ink);font-weight:500}.segmented{display:flex;flex-wrap:wrap}.segmented button{border:1px solid var(--line);border-right:0;background:transparent;padding:9px 12px;cursor:pointer}.segmented button:last-child{border-right:1px solid var(--line)}.segmented button.active{background:var(--ink);color:var(--paper)}.subhead{margin:28px 0 8px;font-size:13px;color:var(--muted);text-transform:uppercase}
.control-field{border-bottom:1px solid var(--line);padding:16px 0}.control-field label{display:block;font-weight:600;margin-bottom:10px}.control-field p{color:var(--muted);font-size:13px;margin:8px 0}.range-row{display:grid;grid-template-columns:minmax(120px,1fr) 74px;gap:14px;align-items:center}.range-row input[type=range]{width:100%;accent-color:var(--accent)}.range-row input[type=number]{width:74px;border:1px solid var(--line);background:var(--paper);padding:8px}.owner-note{border-left:2px solid var(--accent);padding:10px 14px;margin:12px 0 20px;background:var(--soft);color:var(--muted);font-size:13px;line-height:1.6}.inline-actions{display:flex;gap:10px;flex-wrap:wrap;margin:14px 0}.inline-actions a{text-decoration:none}textarea{width:100%;min-height:110px;border:1px solid var(--line);background:var(--paper);padding:12px;resize:vertical;font:inherit;line-height:1.6}
@media(max-width:980px){.shell{grid-template-columns:150px minmax(0,1fr)}.right{position:static;height:auto;grid-column:1/-1;border-left:0;border-top:1px solid var(--line)}.lanes{grid-template-columns:repeat(2,1fr)}}@media(max-width:640px){.shell{display:block}.rail{position:static;height:auto;border-right:0;border-bottom:1px solid var(--line);padding:18px}.nav{grid-template-columns:repeat(3,1fr)}main{padding:24px 18px}h1{font-size:30px}.lanes,.metrics{grid-template-columns:1fr}.lane{min-height:0}.right{border-bottom:0}}
</style></head><body><div class="shell"><aside class="rail"><div class="brand">Operia / Telegram</div><nav class="nav" id="nav">
<button class="active" data-panel="overview">总览</button><button data-panel="rooms">Agent Room</button><button data-panel="agent">Agent</button><button data-panel="heartbeat">Heartbeat</button><button data-panel="mcp">MCP</button><button data-panel="operations">Voice & Media</button><button data-panel="reasoning">Reasoning</button><button data-panel="usage">Tokens & Cache</button><button data-panel="commands">命令</button><button data-panel="models">模型</button><button data-panel="session">会话</button><button data-panel="events">事件</button><button data-panel="security">安全</button>
</nav></aside><main><header><div><div class="meta">PRIVATE COMPANION CONTROL PLANE</div><h1>Command Ledger</h1></div><div class="meta" id="updated">正在连接</div></header>
<section class="panel active" id="overview"><div class="lanes" id="lanes"></div></section>
<section class="panel" id="rooms"><h2>Telegram Agent QA Room</h2><div class="owner-note">P0 固定为 Operia（Operia Worker）+ Codex（本机 <LOCAL_CODEX_BRIDGE>）两个 Agent。Bot ID 是授权主键，Bot Name 只用于显示和 Telegram 现场匹配。新房间默认 wake off；登记两个 Agent 后才可开启 mention/reply。Thread 采用精确绑定：General Topic 留空或填 0/1，其他 Topic 填不小于 2 的 message_thread_id。</div><div id="roomCreate"><div class="subhead">绑定房间</div><div class="inline-actions"><input id="roomChatId" inputmode="numeric" placeholder="Telegram Chat ID"><input id="roomOwnerId" inputmode="numeric" placeholder="Operia Owner User ID"><input id="roomThreadId" inputmode="numeric" placeholder="Thread ID（General 留空/0/1）"><button class="action primary" id="createRoom">现场校验并绑定</button></div></div><div id="roomRows"></div></section>
<section class="panel" id="agent"><h2>Agent 与工具</h2><div id="agentState"></div><div class="rows" id="agentCapabilities"></div></section>
<section class="panel" id="heartbeat"><h2>Heartbeat</h2><div class="owner-note">Heartbeat 执行配置由 Agent 唯一持有；Telegram 只展示继承状态，不保存执行配置副本。</div><div class="inline-actions"><a class="action primary" href="https://agent.example.com/tools/heartbeat">打开 Heartbeat Studio</a></div><div class="rows" id="heartbeatRows"></div></section>
<section class="panel" id="mcp"><h2>MCP</h2><div class="owner-note">Provider 与工具开关由 mcp.example.com 唯一持有；这里通过 Agent Service Binding 修改同一 owner revision，不保存 Telegram 副本。<br><span id="mcpOwner"></span></div><div class="inline-actions"><a class="action" href="https://mcp.example.com/admin">打开 MCP 真源</a><a class="action" href="https://agent.example.com/tools/mcp">打开 Agent MCP</a></div><div id="mcpProviders"></div></section>
<section class="panel" id="operations"><h2>Voice、Media 与工具轨迹</h2><div class="subhead">Voice policy</div><div class="segmented" id="voicePolicies"><button data-mode="off">关闭</button><button data-mode="once">仅下一条</button><button data-mode="auto">按需发声</button></div><div class="segmented" id="voiceModels"><button data-model="realtime">Realtime</button><button data-model="quality">Quality</button><button data-model="expressive">Expressive</button></div><div class="subhead">Provider 与预算</div><div class="rows" id="operationProviders"></div><div class="subhead">Tool trace</div><div class="rows" id="toolTraceRows"></div><div class="subhead">Media outbox</div><div class="rows" id="mediaRows"></div><div class="subhead">Attention required</div><div class="rows" id="attentionRows"></div></section>
<section class="panel" id="reasoning"><h2>Opus Reasoning</h2><div class="owner-note">模型实际执行参数由 Memory Control Plane 统一持有；这里保存的是 Telegram 渠道 override。展示模式只影响 Bot 呈现，不会改变 Opus 的推理执行。<br><span id="executionOwner"></span></div><div class="subhead">Execution override</div><div class="control-field"><label>Adaptive Thinking</label><div class="segmented" id="executionEnabled"><button data-value="false">关闭</button><button data-value="true">开启</button></div><p id="enabledSource"></p></div><div class="control-field"><label>Effort</label><div class="segmented" id="executionEffort"><button data-value="low">Low</button><button data-value="medium">Medium</button><button data-value="high">High</button><button data-value="max">Max</button></div><p id="effortExecutionSource"></p></div><div class="control-field"><label for="tgTemperature">Temperature</label><div class="range-row"><input id="tgTemperature" type="range" min="0" max="1" step="0.05"><input id="tgTemperatureNumber" type="number" min="0" max="1" step="0.05"></div><p>Adaptive Thinking 开启时，Anthropic 不接受自定义 temperature；该值仍保存为统一配置，并在关闭 thinking 后生效。</p><p id="temperatureSource"></p><div class="inline-actions"><button class="action primary" id="saveTemperature">保存 Temperature</button><button class="action" id="resetExecution">清除 Telegram override</button><a class="action" href="https://memory.example.com/admin/inference">打开 Memory 真源</a></div></div><div class="subhead">Telegram presentation</div><div class="control-field"><label>实时任务播报</label><div class="segmented" id="taskProgressModes"><button data-mode="live">Live</button><button data-mode="compact">Compact</button><button data-mode="off">关闭</button></div><p>只影响前台持续状态消息；审计、审批、失败和最终回复始终保留。</p></div><div class="control-field"><label>每条回复的状态栏</label><div class="segmented" id="responseStatusModes"><button data-value="true">开启</button><button data-value="false">关闭</button></div><p>在最终模型消息下展示工具、模型、service tier、tokens 与 cache。</p></div><div class="control-field"><label>Reasoning 展示</label><div class="segmented" id="reasoningModes"><button data-mode="off">关闭</button><button data-mode="summary">摘要</button><button data-mode="debug_trace">调试轨迹</button></div></div><div class="rows" id="reasoningRows"></div></section>
<section class="panel" id="usage"><h2>Tokens & Cache</h2><div id="usageRows"></div><div class="subhead">Cost summary</div><div class="rows" id="costSummary"></div></section>
<section class="panel" id="commands"><h2>斜杠命令</h2><div class="rows" id="commandRows"></div><div class="note" id="commandPolicy"></div><p><button class="action primary" id="syncCommands">同步固定入口到 Telegram</button></p></section>
<section class="panel" id="models"><h2>模型路由</h2><div class="row"><div><strong>Telegram 默认模型</strong><p>只影响私人 Bot，不改变其他 Operia 客户端。</p></div><select id="modelSelect"></select></div></section>
<section class="panel" id="session"><h2>短期会话</h2><div id="sessionState"></div><p><button class="action danger" id="resetSession">清空短期会话</button></p></section>
<section class="panel" id="events"><h2>最近事件</h2><div class="rows" id="eventRows"></div></section>
<section class="panel" id="security"><h2>安全检查</h2><div class="rows" id="securityRows"></div></section>
</main><aside class="rail right"><div class="brand">Control Pages</div><div class="links" id="controlLinks"></div></aside></div><div class="toast" id="toast"></div>
<script>
let csrf='',reasoningData=null,mcpData=null;const $=s=>document.querySelector(s);const toast=m=>{const t=$('#toast');t.textContent=m;t.style.display='block';setTimeout(()=>t.style.display='none',1800)};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,options={}){const headers={'content-type':'application/json',...(options.headers||{})};if(options.method&&options.method!=='GET')headers['x-csrf-token']=csrf;const r=await fetch(path,{...options,headers});if(!r.ok)throw new Error((await r.json()).error||r.statusText);return r.json()}
function lanes(data){$('#lanes').innerHTML=data.lanes.map(x=>'<article class="lane"><h3>'+x.title+'</h3><div class="count">'+x.count+'</div><div class="note">'+x.note+'</div></article>').join('');$('#updated').textContent='更新于 '+new Date(data.generatedAt).toLocaleString()}
function links(items){$('#controlLinks').innerHTML=items.filter(x=>x.enabled).map(x=>'<a class="link" href="'+x.url+'"><strong>'+x.title+'</strong><span>'+x.description+'</span></a>').join('')}
function renderAgent(d){$('#agentState').innerHTML='<div class="row"><div><strong><i class="status '+(d.configured?'':'off')+'"></i>'+(d.configured?'Agent Service Binding 已连接':'Agent 未连接')+'</strong><p><a href="https://agent.example.com/">打开工具目录</a></p></div><span class="meta">健康 Provider '+esc(d.providers?.healthy??0)+'</span></div>';const providers=(d.providerDetails||[]).map(x=>'<a class="row" style="color:inherit;text-decoration:none" href="'+(x.id==='voice'?'https://agent.example.com/tools/voice':'https://agent.example.com/')+'"><div><strong>'+esc(x.name||x.id)+'</strong><p>'+esc(x.id)+' · '+esc(x.toolCount)+' tools</p></div><span class="meta">'+(x.enabled?esc(x.health):'disabled')+' ›</span></a>').join('');const capabilities=(d.capabilities||[]).map(x=>'<div class="row"><div><strong>'+esc(x.label||x.id)+'</strong><p>'+esc(x.description||'')+'</p></div><span class="meta">'+esc(x.status)+'</span></div>').join('');$('#agentCapabilities').innerHTML=providers+capabilities}
function renderHeartbeat(d){const c=d.config||{},r=d.runtime||{};$('#heartbeatRows').innerHTML='<div class="row"><div><strong>Mode</strong><p>owner '+esc(d.owner||'agent.example.com')+' · revision '+esc(d.revision||0)+'</p></div><span class="meta">'+esc(r.mode||c.mode||'unavailable')+'</span></div><div class="row"><div><strong>Last real activity</strong><p>只有自然语言消息可更新</p></div><span class="meta">'+esc(r.lastRealActivityAt||'尚未激活')+'</span></div><div class="row"><div><strong>Daily pulse</strong><p>'+esc(c.timezone||"<YOUR_TIMEZONE>")+' · quiet '+esc(c.quietHours?.start||'--')+'-'+esc(c.quietHours?.end||'--')+'</p></div><span class="meta">'+esc(r.pulsesUsed||0)+' / '+esc(c.dailyLimit??3)+'</span></div><div class="row"><div><strong>First pulse</strong><p>首次只记录决策，不发送、不执行工具</p></div><span class="meta">'+(r.firstPulseDryRunPending?'dry-run pending':'completed')+'</span></div>'}
function renderMcp(d){mcpData=d;$('#mcpOwner').textContent=(d.owner||'mcp.example.com')+' · '+(d.ownerVersion||'unavailable')+' · '+(d.status||'unavailable');$('#mcpProviders').innerHTML=(d.providers||[]).map(p=>'<div class="subhead">'+esc(p.label)+' · '+esc(p.id)+' · '+esc(p.status)+'</div><div class="rows">'+(p.tools||[]).map(t=>'<div class="row"><div><strong>'+esc(t.name)+'</strong><p>'+esc(t.description||'')+'</p></div><span class="meta">'+esc(t.risk||p.risk)+(t.requiresConfirmation?' · approval':'')+' · '+(t.agentCallable?'Agent callable':'not projected')+'</span><button class="action mcp-toggle" data-provider="'+esc(p.id)+'" data-tool="'+esc(t.name)+'" data-enabled="'+(t.enabled?'1':'0')+'">'+(t.enabled?'停用':'启用')+'</button></div>').join('')+'</div>').join('')||'<div class="empty">暂无 MCP Provider</div>'}
function renderReasoning(d){reasoningData=d;const list=Array.isArray(d.execution?.values)?d.execution.values:[];const valueFor=k=>list.find(x=>x.key===k);const enabled=valueFor('memory.inference.reasoning.enabled');const effort=valueFor('memory.inference.reasoning.effort');const temperature=valueFor('memory.inference.sampling.temperature');$('#executionOwner').textContent=d.execution?.ownerDomain?d.execution.ownerDomain+' · '+d.execution.ownerVersion:'';$('#enabledSource').textContent=enabled?'source '+enabled.effectiveSource+' · revision '+enabled.revision:'';$('#effortExecutionSource').textContent=effort?'source '+effort.effectiveSource+' · revision '+effort.revision:'';$('#temperatureSource').textContent=temperature?'source '+temperature.effectiveSource+' · revision '+temperature.revision:'';document.querySelectorAll('#executionEnabled button').forEach(b=>b.classList.toggle('active',String(enabled?.effectiveValue)===b.dataset.value));document.querySelectorAll('#executionEffort button').forEach(b=>b.classList.toggle('active',effort?.effectiveValue===b.dataset.value));document.querySelectorAll('#taskProgressModes button').forEach(b=>b.classList.toggle('active',b.dataset.mode===d.progressMode));document.querySelectorAll('#responseStatusModes button').forEach(b=>b.classList.toggle('active',String(d.expandableResponseStatus)===b.dataset.value));const temp=Number(temperature?.effectiveValue??1);$('#tgTemperature').value=String(temp);$('#tgTemperatureNumber').value=String(temp);document.querySelectorAll('#reasoningModes button').forEach(b=>b.classList.toggle('active',b.dataset.mode===d.mode));if(d.executionError)toast('执行参数暂不可用：'+d.executionError);if(d.mode==='off'){$('#reasoningRows').innerHTML='<div class="empty">Reasoning Trace 已关闭</div>';return}if(d.mode==='summary'){$('#reasoningRows').innerHTML=(d.summaries||[]).map(x=>'<div class="row"><strong>'+esc(x.text)+'</strong><span class="meta">'+new Date(x.createdAt).toLocaleString()+'</span></div>').join('')||'<div class="empty">无 Reasoning summary。模型未主动返回摘要，系统不会生成、恢复或伪造。</div>';return}$('#reasoningRows').innerHTML=(d.events||[]).map(x=>'<div class="row"><div><strong>'+esc(x.eventType)+'</strong><p>'+esc(x.actor)+(x.target?' · '+esc(x.target):'')+'</p></div><span class="meta">'+new Date(x.createdAt).toLocaleString()+'</span></div>').join('')||'<div class="empty">暂无可见调试轨迹</div>'}
function renderUsage(d){$('#usageRows').innerHTML=(d.usage||[]).map(x=>'<details><summary>'+esc(x.model)+' · '+new Date(x.createdAt).toLocaleString()+'</summary><div class="metrics"><div class="metric"><span>model / service tier</span><strong>'+esc(x.model)+' / '+esc(x.serviceTier??'未返回')+'</strong></div><div class="metric"><span>TTFT / total</span><strong>'+(x.ttftMs==null?'不可用':esc(x.ttftMs)+' ms')+' / '+(x.totalMs==null?'未记录':esc(x.totalMs)+' ms')+'</strong></div><div class="metric"><span>input / output</span><strong>'+esc(x.inputTokens??0)+' / '+esc(x.outputTokens??0)+'</strong></div><div class="metric"><span>cache read / create</span><strong>'+esc(x.cacheReadTokens??0)+' / '+esc(x.cacheCreateTokens??0)+'</strong></div></div></details>').join('')||'<div class="empty">暂无 Telegram usage</div>';const c=d.costSummary||{};$('#costSummary').innerHTML='<div class="row"><div><strong>'+esc(c.label||'费用摘要入口')+'</strong><p>'+esc(c.description||'')+'</p></div><span class="meta">'+esc(c.status||'未接入')+'</span></div>'}
function renderOperations(d){const voice=d.voice||{};document.querySelectorAll('#voicePolicies button').forEach(b=>{b.classList.toggle('active',b.dataset.mode===(voice.mode||voice.policy));b.disabled=!voice.enabled&&b.dataset.mode!=='off'});document.querySelectorAll('#voiceModels button').forEach(b=>{b.classList.toggle('active',b.dataset.model===voice.model);b.disabled=!voice.enabled});const a=d.agent||{};const limits=a.limits||{};const providers=(a.providerDetails||[]).map(x=>'<div class="row"><div><strong><i class="status '+(x.enabled?'':'off')+'"></i>'+esc(x.name||x.id)+'</strong><p>'+esc(x.id)+' · '+esc(x.toolCount)+' tools</p></div><span class="meta">'+esc(x.health)+'</span></div>').join('');const budget='<div class="row"><div><strong>Execution limits</strong><p>tool calls '+esc(limits.maxToolCalls??'—')+' · rounds '+esc(limits.maxContinuationRounds??'—')+' · timeout '+esc(limits.providerTimeoutMs??'—')+'ms</p></div><span class="meta">media '+esc(Math.round((limits.maxMediaBytes||d.tgLimits?.maxMediaBytes||0)/1048576))+'MB / '+esc(limits.mediaRetentionHours??24)+'h</span></div>';$('#operationProviders').innerHTML=providers+budget;$('#toolTraceRows').innerHTML=(d.toolRuns||[]).map(x=>'<div class="row"><div><strong>'+esc(x.toolName||'tool')+'</strong><p>'+esc(x.taskId||'')+' · round '+esc(x.round??'—')+' · '+new Date(x.createdAt).toLocaleString()+'</p></div><span class="meta">'+esc(x.status)+(x.elapsedMs==null?'':' · '+esc(x.elapsedMs)+'ms')+'</span></div>').join('')||'<div class="empty">暂无工具调用</div>';$('#mediaRows').innerHTML=(d.mediaOutbox||[]).map(x=>'<div class="row"><div><strong>'+esc(x.method)+'</strong><p>'+esc(x.updated_at)+(x.last_error?' · '+esc(x.last_error):'')+'</p></div><span class="meta">'+esc(x.status)+' · try '+esc(x.attempts)+'</span></div>').join('')||'<div class="empty">暂无媒体投递</div>';$('#attentionRows').innerHTML=(d.attention||[]).map(x=>'<div class="row"><div><strong>'+esc(x.tool_name)+'</strong><p>'+esc(x.updated_at)+(x.last_error?' · '+esc(x.last_error):'')+'</p></div><span class="meta">round '+esc(x.round)+' · try '+esc(x.attempts)+'</span></div>').join('')||'<div class="empty">当前没有需要人工处理的任务</div>'}
async function load(name){if(name==='overview'){lanes(await api('/api/tg/overview'));return}if(name==='agent'){renderAgent(await api('/api/tg/agent-capabilities'));return}if(name==='heartbeat'){renderHeartbeat(await api('/api/tg/heartbeat'));return}if(name==='mcp'){renderMcp(await api('/api/tg/mcp'));return}if(name==='operations'){renderOperations(await api('/api/tg/operations'));return}if(name==='reasoning'){renderReasoning(await api('/api/tg/reasoning'));return}if(name==='usage'){renderUsage(await api('/api/tg/usage'));return}if(name==='commands'){const d=await api('/api/tg/commands');$('#commandRows').innerHTML=d.commands.map(x=>'<div class="row"><strong>/'+esc(x.displayCommand||x.command)+'</strong><span class="meta">'+esc(x.description)+'</span></div>').join('');$('#commandPolicy').textContent=d.catalogPolicy||'';return}if(name==='models'){const d=await api('/api/tg/models');$('#modelSelect').innerHTML=d.models.map(x=>'<option '+(x===d.selected?'selected':'')+'>'+esc(x)+'</option>').join('');return}if(name==='session'){const d=await api('/api/tg/session');$('#sessionState').innerHTML='<div class="row"><div><strong>'+(d.configured?'已绑定私人聊天':'尚未配置 Chat ID')+'</strong><p>'+(d.state?'最近更新：'+esc(d.state.updated_at)+'，摘要字符：'+esc(d.state.summary_chars):'暂无短期会话')+'</p></div></div>';return}if(name==='events'){const d=await api('/api/tg/events');$('#eventRows').innerHTML=d.events.length?d.events.map(x=>{let m={};try{m=JSON.parse(x.metadata_json||'{}')}catch{}const detail=[m.toolName,m.taskId,m.round==null?'':'round '+m.round].filter(Boolean).join(' · ');return '<div class="row"><div><strong>'+esc(x.event_type)+'</strong><p>'+esc(x.created_at)+(detail?' · '+esc(detail):'')+'</p></div><span class="meta">'+esc(x.status)+'</span></div>'}).join(''):'<div class="empty">暂无事件</div>';return}if(name==='security'){const d=await api('/api/tg/security');$('#securityRows').innerHTML=Object.entries(d).map(([k,v])=>'<div class="row"><strong><i class="status '+(v?'':'off')+'"></i>'+esc(k)+'</strong><span class="meta">'+(v?'已配置':'未配置')+'</span></div>').join('')}}
async function activate(name){const b=document.querySelector('.nav button[data-panel="'+name+'"]');const panel=$('#'+name);if(!b||!panel)return;document.querySelectorAll('.nav button,.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');panel.classList.add('active');location.hash=name==='overview'?'':name;await load(name)}
$('#nav').addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;try{await activate(b.dataset.panel)}catch(e){toast(e.message)}});
$('#mcpProviders').addEventListener('click',async e=>{const b=e.target.closest('.mcp-toggle');if(!b||!mcpData?.etag)return;b.disabled=true;try{const d=await api('/api/tg/mcp/tools',{method:'PATCH',headers:{'if-match':mcpData.etag},body:JSON.stringify({provider:b.dataset.provider,tool:b.dataset.tool,enabled:b.dataset.enabled!=='1'})});renderMcp(d);toast('MCP owner state 已更新')}catch(error){toast(error.message);await load('mcp')}});
$('#syncCommands').onclick=async()=>{try{const result=await api('/api/tg/commands/sync',{method:'POST',body:'{}'});toast('Telegram 原生命令菜单已同步：@'+result.bot.username+' · '+result.verifiedCount+' 条 · '+result.verifiedTargets.length+' 个作用域投影已核验')}catch(e){toast(e.message)}};
$('#modelSelect').onchange=async e=>{try{await api('/api/tg/model',{method:'PUT',body:JSON.stringify({model:e.target.value})});toast('模型已更新')}catch(e){toast(e.message)}};
$('#resetSession').onclick=async()=>{if(!confirm('只清空 Telegram 短期会话，长期记忆保持不变。继续？'))return;try{await api('/api/tg/session/reset',{method:'POST',body:'{}'});toast('短期会话已清空');load('session')}catch(e){toast(e.message)}};
$('#reasoningModes').onclick=async e=>{const b=e.target.closest('button');if(!b)return;try{await api('/api/tg/reasoning',{method:'PUT',body:JSON.stringify({mode:b.dataset.mode})});await load('reasoning');toast('Reasoning 模式已更新')}catch(e){toast(e.message)}};
$('#taskProgressModes').onclick=async e=>{const b=e.target.closest('button');if(!b)return;try{await api('/api/tg/presentation',{method:'PUT',body:JSON.stringify({progressMode:b.dataset.mode})});await load('reasoning');toast('任务播报模式已更新')}catch(e){toast(e.message)}};
$('#responseStatusModes').onclick=async e=>{const b=e.target.closest('button');if(!b)return;try{await api('/api/tg/presentation',{method:'PUT',body:JSON.stringify({expandableResponseStatus:b.dataset.value==='true'})});await load('reasoning');toast('回复状态栏已更新')}catch(e){toast(e.message)}};
async function updateExecution(key,value,reset=false){await api('/api/tg/reasoning-execution',{method:'PUT',body:JSON.stringify({key,value,reset})})}
$('#executionEnabled').onclick=async e=>{const b=e.target.closest('button');if(!b)return;try{await updateExecution('memory.inference.reasoning.enabled',b.dataset.value==='true');await load('reasoning');toast('Adaptive Thinking override 已更新')}catch(e){toast(e.message)}};
$('#executionEffort').onclick=async e=>{const b=e.target.closest('button');if(!b)return;try{await updateExecution('memory.inference.reasoning.effort',b.dataset.value);await load('reasoning');toast('Effort override 已更新')}catch(e){toast(e.message)}};
$('#tgTemperature').oninput=e=>{$('#tgTemperatureNumber').value=e.target.value};$('#tgTemperatureNumber').oninput=e=>{$('#tgTemperature').value=e.target.value};
$('#saveTemperature').onclick=async()=>{try{const value=Number($('#tgTemperatureNumber').value);if(!Number.isFinite(value)||value<0||value>1)throw new Error('Temperature 必须在 0 到 1 之间');await updateExecution('memory.inference.sampling.temperature',value);await load('reasoning');toast('Temperature override 已更新')}catch(e){toast(e.message)}};
$('#resetExecution').onclick=async()=>{try{for(const key of ['memory.inference.reasoning.enabled','memory.inference.reasoning.effort','memory.inference.sampling.temperature'])await updateExecution(key,null,true);await load('reasoning');toast('Telegram execution override 已清除')}catch(e){toast(e.message)}};
async function updateVoice(patch){try{const current=await api('/api/tg/operations');const voice=current.voice||{};await api('/api/tg/voice',{method:'PUT',body:JSON.stringify({mode:patch.mode||voice.mode||voice.policy||'off',model:patch.model||voice.model||'expressive'})});await load('operations');toast('语音模式已更新')}catch(e){toast(e.message)}}
$('#voicePolicies').onclick=e=>{const b=e.target.closest('button');if(b&&!b.disabled)updateVoice({mode:b.dataset.mode})};$('#voiceModels').onclick=e=>{const b=e.target.closest('button');if(b&&!b.disabled)updateVoice({model:b.dataset.model})};
(async()=>{try{const d=await api('/api/tg/bootstrap');csrf=d.csrfToken||'';lanes(d.overview);links(d.links);const initial=location.hash.slice(1);if(initial&&initial!=='overview')await activate(initial)}catch(e){document.body.innerHTML='<main style="padding:40px"><h1>需要登录</h1><p>请先通过 Cloudflare Access 登录 example.com 域。</p></main>'}})();
</script><script>
	function renderRooms(d){
	  const rooms=d.rooms||[];
	  $('#roomCreate').style.display=rooms.length?'none':'block';
	  $('#roomRows').innerHTML='<div class="owner-note">全局运行门：'+(d.enabled?'enabled':'disabled')+'。Queue backlog 未向 Worker 暴露时明确显示 unavailable，不用 D1 推断为 0。</div>'+rooms.map(r=>{
	    const shared=r.shared||{},summary=shared.summary||{},pin=shared.pin||{},routing=r.routing||{},queue=routing.roomQueue||{},durable=r.durableState||{},loop=r.loopGuard||{},attention=r.attention||{};
	    const agents=(r.agents||[]).map(a=>'<div class="row"><div><strong>@'+esc(a.botUsername||a.botName)+'</strong><p>Bot ID '+esc(a.botUserId)+' · '+esc(a.runtimeKind)+' · verified '+esc(a.verifiedAt)+'</p></div><span class="meta">'+esc(a.status)+' / '+esc(a.membershipStatus)+' · B2B '+esc(a.botToBotMode)+'</span>'+(a.runtimeKind==='operia_worker'?'':'<button class="action room-agent-status" data-room="'+esc(r.id)+'" data-bot="'+esc(a.botUserId)+'" data-revision="'+esc(r.revision)+'" data-status="'+(a.status==='active'?'suspended':'active')+'">'+(a.status==='active'?'暂停 Codex':'恢复 Codex')+'</button>')+'</div>').join('');
	    const events=(r.recentEvents||[]).map(x=>'<div class="row"><div><strong>'+esc(x.eventType)+'</strong><p>'+esc(x.createdAt)+'</p></div><span class="meta">'+esc(x.status)+'</span></div>').join('')||'<div class="empty">暂无房间事件</div>';
	    const attentionRows=(attention.items||[]).map(x=>'<div class="row"><div><strong>'+esc(x.kind)+' · '+esc(x.status)+'</strong><p>'+esc(x.updatedAt)+(x.errorCode?' · '+esc(x.errorCode):'')+'</p></div><span class="meta">'+esc(x.id)+'</span></div>').join('')||'<div class="empty">当前无 attention</div>';
	    return '<div class="subhead">'+esc(r.title)+' · room revision '+esc(r.revision)+'</div>'
	      +'<div class="owner-note">'+esc(r.chatType)+' · '+esc(r.topic?.policy)+' / '+esc(r.topic?.threadKey)+' · wake '+esc(routing.wakePolicy)+'<br>namespace '+esc(routing.namespace)+' · private Memory '+esc(routing.privateMemory)+' · Queue '+esc(queue.queue)+' / '+esc(queue.backlog?.status)+'</div>'
	      +'<div class="inline-actions"><button class="action '+(routing.wakePolicy==='off'?'primary':'danger')+' room-wake" data-room="'+esc(r.id)+'" data-revision="'+esc(r.revision)+'" data-wake="'+(routing.wakePolicy==='off'?'mention_or_reply':'off')+'">'+(routing.wakePolicy==='off'?'开启 mention/reply':'立即关闭整间房')+'</button><button class="action '+(summary.mode==='off'?'primary':'danger')+' room-summary" data-room="'+esc(r.id)+'" data-revision="'+esc(summary.controlRevision||0)+'" data-mode="'+(summary.mode==='off'?'active':'off')+'">'+(summary.mode==='off'?'开启 rolling summary':'停止 rolling summary')+'</button></div>'
	      +'<div class="rows">'+agents+'</div>'
	      +((r.agents||[]).length<2?'<div class="subhead">登记 Codex</div><div class="inline-actions"><input class="new-agent-name" data-room="'+esc(r.id)+'" placeholder="Codex Bot Name"><input class="new-agent-id" data-room="'+esc(r.id)+'" inputmode="numeric" placeholder="Codex Bot ID"><button class="action primary add-room-agent" data-room="'+esc(r.id)+'" data-revision="'+esc(r.revision)+'">现场匹配并登记</button></div>':'')
	      +'<div class="subhead">Routing / Queue / Loop</div><div class="metrics"><div class="metric"><span>pending inbox</span><strong>'+esc(durable.pendingInbox||0)+'</strong></div><div class="metric"><span>loop guard</span><strong>'+esc(loop.acceptedBotTurns||0)+' / '+esc(loop.limit||5)+'</strong></div><div class="metric"><span>transcript</span><strong>'+esc(shared.transcript?.count||0)+' / '+esc(shared.transcript?.maxItems||8)+'</strong></div><div class="metric"><span>attention</span><strong>'+esc(attention.count||0)+'</strong></div></div>'
	      +'<div class="subhead">Rolling summary · '+esc(summary.status)+' · revision '+esc(summary.revision||0)+'</div><div class="owner-note">'+esc(summary.text||'尚无摘要；开启后只使用本房间 2h / 4-exchange transcript，通过 Workers AI 有界生成。')+(summary.errorCode?'<br>attention: '+esc(summary.errorCode):'')+'</div>'
	      +'<div class="subhead">Owner Pin · revision '+esc(pin.revision||0)+'</div><textarea class="room-pin-text" data-room="'+esc(r.id)+'" maxlength="4000" placeholder="只保存工作群共享锚点，不写入私人 Memory。">'+esc(pin.text||'')+'</textarea><div class="inline-actions"><button class="action primary room-pin-save" data-room="'+esc(r.id)+'" data-revision="'+esc(pin.revision||0)+'">CAS 保存 Pin</button><button class="action room-pin-clear" data-room="'+esc(r.id)+'" data-revision="'+esc(pin.revision||0)+'">清除 Pin</button></div>'
	      +'<details><summary>Attention · '+esc(attention.count||0)+'</summary><div class="rows">'+attentionRows+'</div></details><details><summary>最近房间事件</summary><div class="rows">'+events+'</div></details>';
	  }).join('')||'<div class="empty">尚未绑定 Agent Room</div>';
	}
const baseLoad=load;load=async name=>{if(name==='rooms'){renderRooms(await api('/api/tg/rooms'));return}return baseLoad(name)};
$('#createRoom').onclick=async()=>{try{await api('/api/tg/rooms',{method:'POST',body:JSON.stringify({chatId:$('#roomChatId').value,ownerUserId:$('#roomOwnerId').value,threadId:$('#roomThreadId').value||0})});await load('rooms');toast('Agent Room 已通过 Telegram 现场校验并绑定')}catch(e){toast(e.message)}};
	$('#roomRows').onclick=async e=>{
	  const add=e.target.closest('.add-room-agent'),status=e.target.closest('.room-agent-status'),wake=e.target.closest('.room-wake'),summary=e.target.closest('.room-summary'),save=e.target.closest('.room-pin-save'),clear=e.target.closest('.room-pin-clear');
	  try{
	    if(add){const roomId=add.dataset.room;await api('/api/tg/room-agents',{method:'POST',body:JSON.stringify({roomId,revision:Number(add.dataset.revision),botName:document.querySelector('.new-agent-name[data-room="'+roomId+'"]').value,botUserId:document.querySelector('.new-agent-id[data-room="'+roomId+'"]').value,runtimeKind:'cc_connect'})});toast('Codex 已按 Bot ID 与 Telegram 现场身份匹配')}
	    else if(status){await api('/api/tg/room-agents',{method:'PATCH',body:JSON.stringify({roomId:status.dataset.room,botUserId:status.dataset.bot,status:status.dataset.status,revision:Number(status.dataset.revision)})});toast('Codex 状态已更新')}
	    else if(wake){await api('/api/tg/rooms/wake',{method:'PATCH',body:JSON.stringify({roomId:wake.dataset.room,wakePolicy:wake.dataset.wake,revision:Number(wake.dataset.revision)})});toast(wake.dataset.wake==='off'?'整间房已关闭':'mention/reply 已开启')}
	    else if(summary){await api('/api/tg/rooms/summary',{method:'PATCH',body:JSON.stringify({roomId:summary.dataset.room,mode:summary.dataset.mode,revision:Number(summary.dataset.revision)})});toast(summary.dataset.mode==='active'?'rolling summary 已开启':'rolling summary 已停止')}
	    else if(save||clear){const button=save||clear,roomId=button.dataset.room,text=clear?'':document.querySelector('.room-pin-text[data-room="'+roomId+'"]').value;await api('/api/tg/rooms/pin',{method:'PUT',body:JSON.stringify({roomId,text,revision:Number(button.dataset.revision)})});toast(clear?'Owner Pin 已清除':'Owner Pin 已保存')}
	    else return;
	    await load('rooms');
	  }catch(error){toast(error.message);await load('rooms')}
	};
</script></body></html>`, { headers: { "content-type": "text/html; charset=utf-8", "cache-control": "no-store", "content-security-policy": "default-src 'self'; style-src 'unsafe-inline' https://fonts.googleapis.com; font-src https://fonts.gstatic.com; script-src 'unsafe-inline'; connect-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'", "x-frame-options": "DENY", "x-robots-tag": "noindex" } });
}
