/**
 * H-C0 / H-C1 — Internal Service Route Registry.
 *
 * Machine-readable inventory of `/service/*` routes. H-C1 wires the Memory
 * Control vertical slice into enforcement via `src/security/credentials.ts`.
 */

export type CallerEvidence = "confirmed" | "planned" | "external";

export type InternalServiceCaller = {
  sourceDomain: string;
  serviceId: string;
  evidence: CallerEvidence;
  sourcePath?: string;
};

export type DeploymentTarget =
  | "memory"
  | "agent"
  | "tgbot"
  | "health"
  | "think-gate-d-canary"
  | string;

export type InternalServiceRoute = {
  id: string;
  deploymentTarget: DeploymentTarget;
  host: string;
  path: string;
  methods: string[];
  credentialClass: "internal_service" | "domain_session" | "application_api";
  credentialEnv?: string;
  callers: InternalServiceCaller[];
  /**
   * A bearer-less internal route is still an internal route: it is reachable
   * only on the internal hostname. This flag marks the exception explicitly so
   * it is not confused with a public route.
   */
  bearerlessInternalException?: boolean;
};

export const INTERNAL_SERVICE_ROUTES: InternalServiceRoute[] = [
  // ---------------------------------------------------------------------------
  // <MEMORY_SERVICE>.internal
  // ---------------------------------------------------------------------------
  {
    id: "memory:domain-session:verify",
    deploymentTarget: "memory",
    host: "<MEMORY_SERVICE>.internal",
    path: "/service/domain-session/verify",
    methods: ["POST"],
    credentialClass: "internal_service",
    credentialEnv: "HEALTH_SESSION_VERIFY_BEARER",
    callers: [{
      sourceDomain: "health.example.com",
      serviceId: "<HEALTH_SERVICE>-session-verifier",
      evidence: "confirmed",
      sourcePath: "src/health/sessionVerifier.ts",
    }],
  },
  {
    id: "memory:presentation:capabilities",
    deploymentTarget: "memory",
    host: "<MEMORY_SERVICE>.internal",
    path: "/service/presentation/capabilities",
    methods: ["GET"],
    credentialClass: "internal_service",
    callers: [{
      sourceDomain: "tgbot.example.com",
      serviceId: "telegram-agent",
      evidence: "confirmed",
      sourcePath: "src/tg/richResultRuntime.ts",
    }],
    bearerlessInternalException: true,
  },
  {
    id: "memory:heartbeat:inference",
    deploymentTarget: "memory",
    host: "<MEMORY_SERVICE>.internal",
    path: "/service/heartbeat/inference",
    methods: ["POST"],
    credentialClass: "application_api",
    credentialEnv: "TG_CHAT_API_KEY",
    callers: [{
      sourceDomain: "tgbot.example.com",
      serviceId: "telegram-agent",
      evidence: "confirmed",
      sourcePath: "src/tg/heartbeat.ts",
    }],
  },
  {
    id: "memory:think:approval-wake",
    deploymentTarget: "memory",
    host: "<MEMORY_SERVICE>.internal",
    path: "/service/think/approval-wake",
    methods: ["POST"],
    credentialClass: "application_api",
    credentialEnv: "TG_CHAT_API_KEY",
    callers: [{
      sourceDomain: "tgbot.example.com",
      serviceId: "telegram-agent",
      evidence: "confirmed",
      sourcePath: "src/tg/thinkApprovalWakeClient.ts",
    }],
  },
  {
    id: "memory:think:sdk-action-decision",
    deploymentTarget: "memory",
    host: "<MEMORY_SERVICE>.internal",
    path: "/service/think/sdk-action-decision",
    methods: ["POST"],
    credentialClass: "application_api",
    credentialEnv: "TG_CHAT_API_KEY",
    callers: [{
      sourceDomain: "tgbot.example.com",
      serviceId: "telegram-agent",
      evidence: "confirmed",
      sourcePath: "src/tg/thinkSdkActionDecisionClient.ts",
    }],
  },
  {
    id: "memory:think:codemode-wake",
    deploymentTarget: "memory",
    host: "<MEMORY_SERVICE>.internal",
    path: "/service/think/codemode-wake",
    methods: ["POST"],
    credentialClass: "application_api",
    credentialEnv: "TG_CHAT_API_KEY",
    callers: [{
      sourceDomain: "tgbot.example.com",
      serviceId: "telegram-agent",
      evidence: "confirmed",
      sourcePath: "src/tg/thinkCodeModeWakeClient.ts",
    }],
  },
  {
    id: "memory:conversation:state",
    deploymentTarget: "memory",
    host: "<MEMORY_SERVICE>.internal",
    path: "/service/conversation/state",
    methods: ["GET", "POST", "DELETE"],
    credentialClass: "application_api",
    credentialEnv: "TG_CHAT_API_KEY",
    callers: [{
      sourceDomain: "tgbot.example.com",
      serviceId: "telegram-agent",
      evidence: "confirmed",
      sourcePath: "src/tg/conversationClient.ts",
    }],
  },
  {
    id: "memory:control:bootstrap",
    deploymentTarget: "memory",
    host: "<MEMORY_SERVICE>.internal",
    path: "/service/control/bootstrap",
    methods: ["GET"],
    credentialClass: "internal_service",
    credentialEnv: "MEMORY_CONTROL_SERVICE_BEARER",
    callers: [
      {
        sourceDomain: "tgbot.example.com",
        serviceId: "telegram-agent",
        evidence: "confirmed",
        sourcePath: "src/tg/memoryControlClient.ts",
      },
      {
        sourceDomain: "agent.example.com",
        serviceId: "agent-control-projection",
        evidence: "planned",
      },
      {
        sourceDomain: "operia-dashboard",
        serviceId: "operia-dashboard-memory-projection",
        evidence: "planned",
      },
    ],
  },
  {
    id: "memory:control:values",
    deploymentTarget: "memory",
    host: "<MEMORY_SERVICE>.internal",
    path: "/service/control/values",
    methods: ["GET"],
    credentialClass: "internal_service",
    credentialEnv: "MEMORY_CONTROL_SERVICE_BEARER",
    callers: [
      {
        sourceDomain: "tgbot.example.com",
        serviceId: "telegram-agent",
        evidence: "confirmed",
        sourcePath: "src/tg/memoryControlClient.ts",
      },
      {
        sourceDomain: "agent.example.com",
        serviceId: "agent-control-projection",
        evidence: "planned",
      },
      {
        sourceDomain: "operia-dashboard",
        serviceId: "operia-dashboard-memory-projection",
        evidence: "planned",
      },
    ],
  },
  {
    id: "memory:control:effective",
    deploymentTarget: "memory",
    host: "<MEMORY_SERVICE>.internal",
    path: "/service/control/effective",
    methods: ["GET", "POST"],
    credentialClass: "internal_service",
    credentialEnv: "MEMORY_CONTROL_SERVICE_BEARER",
    callers: [
      {
        sourceDomain: "tgbot.example.com",
        serviceId: "telegram-agent",
        evidence: "confirmed",
        sourcePath: "src/tg/memoryControlClient.ts",
      },
      {
        sourceDomain: "agent.example.com",
        serviceId: "agent-control-projection",
        evidence: "planned",
      },
      {
        sourceDomain: "operia-dashboard",
        serviceId: "operia-dashboard-memory-projection",
        evidence: "planned",
      },
    ],
  },
  {
    id: "memory:control:events",
    deploymentTarget: "memory",
    host: "<MEMORY_SERVICE>.internal",
    path: "/service/control/events",
    methods: ["GET"],
    credentialClass: "internal_service",
    credentialEnv: "MEMORY_CONTROL_SERVICE_BEARER",
    callers: [
      {
        sourceDomain: "tgbot.example.com",
        serviceId: "telegram-agent",
        evidence: "confirmed",
        sourcePath: "src/tg/memoryControlClient.ts",
      },
      {
        sourceDomain: "agent.example.com",
        serviceId: "agent-control-projection",
        evidence: "planned",
      },
      {
        sourceDomain: "operia-dashboard",
        serviceId: "operia-dashboard-memory-projection",
        evidence: "planned",
      },
    ],
  },
  {
    id: "memory:control:cache-health",
    deploymentTarget: "memory",
    host: "<MEMORY_SERVICE>.internal",
    path: "/service/control/cache-health",
    methods: ["GET"],
    credentialClass: "internal_service",
    credentialEnv: "MEMORY_CONTROL_SERVICE_BEARER",
    callers: [
      {
        sourceDomain: "tgbot.example.com",
        serviceId: "telegram-agent",
        evidence: "confirmed",
        sourcePath: "src/tg/memoryControlClient.ts",
      },
      {
        sourceDomain: "agent.example.com",
        serviceId: "agent-control-projection",
        evidence: "planned",
      },
      {
        sourceDomain: "operia-dashboard",
        serviceId: "operia-dashboard-memory-projection",
        evidence: "planned",
      },
    ],
  },
  {
    id: "memory:control:models",
    deploymentTarget: "memory",
    host: "<MEMORY_SERVICE>.internal",
    path: "/service/control/models",
    methods: ["GET"],
    credentialClass: "internal_service",
    credentialEnv: "MEMORY_CONTROL_SERVICE_BEARER",
    callers: [
      {
        sourceDomain: "tgbot.example.com",
        serviceId: "telegram-agent",
        evidence: "confirmed",
        sourcePath: "src/tg/memoryControlClient.ts",
      },
      {
        sourceDomain: "agent.example.com",
        serviceId: "agent-control-projection",
        evidence: "planned",
      },
      {
        sourceDomain: "operia-dashboard",
        serviceId: "operia-dashboard-memory-projection",
        evidence: "planned",
      },
    ],
  },
  {
    id: "memory:control:think-observation",
    deploymentTarget: "memory",
    host: "<MEMORY_SERVICE>.internal",
    path: "/service/control/think-observation",
    methods: ["GET"],
    credentialClass: "internal_service",
    credentialEnv: "MEMORY_CONTROL_SERVICE_BEARER",
    callers: [
      {
        sourceDomain: "tgbot.example.com",
        serviceId: "telegram-agent",
        evidence: "confirmed",
        sourcePath: "src/tg/memoryControlClient.ts",
      },
      {
        sourceDomain: "agent.example.com",
        serviceId: "agent-control-projection",
        evidence: "planned",
      },
      {
        sourceDomain: "operia-dashboard",
        serviceId: "operia-dashboard-memory-projection",
        evidence: "planned",
      },
    ],
  },
  {
    id: "memory:control:overrides",
    deploymentTarget: "memory",
    host: "<MEMORY_SERVICE>.internal",
    path: "/service/control/overrides/:key",
    methods: ["PUT", "DELETE"],
    credentialClass: "internal_service",
    credentialEnv: "MEMORY_CONTROL_SERVICE_BEARER",
    callers: [
      {
        sourceDomain: "tgbot.example.com",
        serviceId: "telegram-agent",
        evidence: "confirmed",
        sourcePath: "src/tg/memoryControlClient.ts",
      },
      {
        sourceDomain: "agent.example.com",
        serviceId: "agent-control-projection",
        evidence: "planned",
      },
      {
        sourceDomain: "operia-dashboard",
        serviceId: "operia-dashboard-memory-projection",
        evidence: "planned",
      },
    ],
  },
  {
    id: "memory:control:values-key",
    deploymentTarget: "memory",
    host: "<MEMORY_SERVICE>.internal",
    path: "/service/control/values/:key",
    methods: ["PUT"],
    credentialClass: "internal_service",
    credentialEnv: "MEMORY_CONTROL_SERVICE_BEARER",
    callers: [
      {
        sourceDomain: "tgbot.example.com",
        serviceId: "telegram-agent",
        evidence: "confirmed",
        sourcePath: "src/tg/memoryControlClient.ts",
      },
      {
        sourceDomain: "agent.example.com",
        serviceId: "agent-control-projection",
        evidence: "planned",
      },
      {
        sourceDomain: "operia-dashboard",
        serviceId: "operia-dashboard-memory-projection",
        evidence: "planned",
      },
    ],
  },
  {
    id: "memory:control:next-turn-claim",
    deploymentTarget: "memory",
    host: "<MEMORY_SERVICE>.internal",
    path: "/service/control/next-turn/claim",
    methods: ["POST"],
    credentialClass: "internal_service",
    credentialEnv: "MEMORY_CONTROL_SERVICE_BEARER",
    callers: [
      {
        sourceDomain: "tgbot.example.com",
        serviceId: "telegram-agent",
        evidence: "confirmed",
        sourcePath: "src/tg/memoryControlClient.ts",
      },
      {
        sourceDomain: "agent.example.com",
        serviceId: "agent-control-projection",
        evidence: "planned",
      },
      {
        sourceDomain: "operia-dashboard",
        serviceId: "operia-dashboard-memory-projection",
        evidence: "planned",
      },
    ],
  },
  {
    id: "memory:control:next-turn-release",
    deploymentTarget: "memory",
    host: "<MEMORY_SERVICE>.internal",
    path: "/service/control/next-turn/release",
    methods: ["POST"],
    credentialClass: "internal_service",
    credentialEnv: "MEMORY_CONTROL_SERVICE_BEARER",
    callers: [
      {
        sourceDomain: "tgbot.example.com",
        serviceId: "telegram-agent",
        evidence: "confirmed",
        sourcePath: "src/tg/memoryControlClient.ts",
      },
      {
        sourceDomain: "agent.example.com",
        serviceId: "agent-control-projection",
        evidence: "planned",
      },
      {
        sourceDomain: "operia-dashboard",
        serviceId: "operia-dashboard-memory-projection",
        evidence: "planned",
      },
    ],
  },

  // ---------------------------------------------------------------------------
  // <AGENT_SERVICE>.internal
  // ---------------------------------------------------------------------------
  {
    id: "agent:think:catalog",
    deploymentTarget: "agent",
    host: "<AGENT_SERVICE>.internal",
    path: "/service/think/catalog",
    methods: ["GET"],
    credentialClass: "internal_service",
    credentialEnv: "AGENT_THINK_SERVICE_BEARER",
    callers: [{
      sourceDomain: "memory.example.com",
      serviceId: "<MEMORY_SERVICE>-think-gateway",
      evidence: "confirmed",
      sourcePath: "src/memory/think/productionAgentGatewayClient.ts",
    }],
  },
  {
    id: "agent:think:search",
    deploymentTarget: "agent",
    host: "<AGENT_SERVICE>.internal",
    path: "/service/think/search",
    methods: ["POST"],
    credentialClass: "internal_service",
    credentialEnv: "AGENT_THINK_SERVICE_BEARER",
    callers: [{
      sourceDomain: "memory.example.com",
      serviceId: "<MEMORY_SERVICE>-think-gateway",
      evidence: "confirmed",
      sourcePath: "src/memory/think/productionAgentGatewayClient.ts",
    }],
  },
  {
    id: "agent:think:describe",
    deploymentTarget: "agent",
    host: "<AGENT_SERVICE>.internal",
    path: "/service/think/describe",
    methods: ["POST"],
    credentialClass: "internal_service",
    credentialEnv: "AGENT_THINK_SERVICE_BEARER",
    callers: [{
      sourceDomain: "memory.example.com",
      serviceId: "<MEMORY_SERVICE>-think-gateway",
      evidence: "confirmed",
      sourcePath: "src/memory/think/productionAgentGatewayClient.ts",
    }],
  },
  {
    id: "agent:think:execute",
    deploymentTarget: "agent",
    host: "<AGENT_SERVICE>.internal",
    path: "/service/think/execute",
    methods: ["POST"],
    credentialClass: "internal_service",
    credentialEnv: "AGENT_THINK_SERVICE_BEARER",
    callers: [{
      sourceDomain: "memory.example.com",
      serviceId: "<MEMORY_SERVICE>-think-gateway",
      evidence: "confirmed",
      sourcePath: "src/memory/think/productionAgentGatewayClient.ts",
    }],
  },
  {
    id: "agent:think:actions:preflight",
    deploymentTarget: "agent",
    host: "<AGENT_SERVICE>.internal",
    path: "/service/think/actions/preflight",
    methods: ["POST"],
    credentialClass: "internal_service",
    credentialEnv: "AGENT_THINK_SERVICE_BEARER",
    callers: [{
      sourceDomain: "memory.example.com",
      serviceId: "<MEMORY_SERVICE>-think-gateway",
      evidence: "confirmed",
      sourcePath: "src/memory/think/productionAgentGatewayClient.ts",
    }],
  },
  {
    id: "agent:think:actions:execute",
    deploymentTarget: "agent",
    host: "<AGENT_SERVICE>.internal",
    path: "/service/think/actions/execute",
    methods: ["POST"],
    credentialClass: "internal_service",
    credentialEnv: "AGENT_THINK_SERVICE_BEARER",
    callers: [{
      sourceDomain: "memory.example.com",
      serviceId: "<MEMORY_SERVICE>-think-gateway",
      evidence: "confirmed",
      sourcePath: "src/memory/think/productionAgentGatewayClient.ts",
    }],
  },
  {
    id: "agent:think:actions:revoke",
    deploymentTarget: "agent",
    host: "<AGENT_SERVICE>.internal",
    path: "/service/think/actions/revoke",
    methods: ["POST"],
    credentialClass: "internal_service",
    credentialEnv: "AGENT_THINK_SERVICE_BEARER",
    callers: [{
      sourceDomain: "memory.example.com",
      serviceId: "<MEMORY_SERVICE>-think-gateway",
      evidence: "confirmed",
      sourcePath: "src/memory/think/productionAgentGatewayClient.ts",
    }],
  },
  {
    id: "agent:think:codemode",
    deploymentTarget: "agent",
    host: "<AGENT_SERVICE>.internal",
    path: "/service/think/codemode",
    methods: ["POST"],
    credentialClass: "internal_service",
    credentialEnv: "AGENT_THINK_SERVICE_BEARER",
    callers: [{
      sourceDomain: "memory.example.com",
      serviceId: "<MEMORY_SERVICE>-think-gateway",
      evidence: "confirmed",
      sourcePath: "src/memory/think/productionAgentGatewayClient.ts",
    }],
  },
  {
    id: "agent:think:codemode:resume",
    deploymentTarget: "agent",
    host: "<AGENT_SERVICE>.internal",
    path: "/service/think/codemode/resume",
    methods: ["POST"],
    credentialClass: "internal_service",
    credentialEnv: "AGENT_THINK_SERVICE_BEARER",
    callers: [{
      sourceDomain: "memory.example.com",
      serviceId: "<MEMORY_SERVICE>-think-gateway",
      evidence: "confirmed",
      sourcePath: "src/memory/think/productionAgentGatewayClient.ts",
    }],
  },
  {
    id: "agent:think:codemode:status",
    deploymentTarget: "agent",
    host: "<AGENT_SERVICE>.internal",
    path: "/service/think/codemode/status",
    methods: ["POST"],
    credentialClass: "internal_service",
    credentialEnv: "AGENT_THINK_SERVICE_BEARER",
    callers: [{
      sourceDomain: "memory.example.com",
      serviceId: "<MEMORY_SERVICE>-think-gateway",
      evidence: "confirmed",
      sourcePath: "src/memory/think/productionAgentGatewayClient.ts",
    }],
  },
  {
    id: "agent:think:codemode:stop",
    deploymentTarget: "agent",
    host: "<AGENT_SERVICE>.internal",
    path: "/service/think/codemode/stop",
    methods: ["POST"],
    credentialClass: "internal_service",
    credentialEnv: "AGENT_THINK_SERVICE_BEARER",
    callers: [{
      sourceDomain: "memory.example.com",
      serviceId: "<MEMORY_SERVICE>-think-gateway",
      evidence: "confirmed",
      sourcePath: "src/memory/think/productionAgentGatewayClient.ts",
    }],
  },
  {
    id: "agent:think:task:complete",
    deploymentTarget: "agent",
    host: "<AGENT_SERVICE>.internal",
    path: "/service/think/task/complete",
    methods: ["POST"],
    credentialClass: "internal_service",
    credentialEnv: "AGENT_THINK_SERVICE_BEARER",
    callers: [{
      sourceDomain: "memory.example.com",
      serviceId: "<MEMORY_SERVICE>-think-gateway",
      evidence: "confirmed",
      sourcePath: "src/memory/think/productionAgentGatewayClient.ts",
    }],
  },
  {
    id: "agent:think:approvals:receipt",
    deploymentTarget: "agent",
    host: "<AGENT_SERVICE>.internal",
    path: "/service/think/approvals/:ticketId/receipt",
    methods: ["POST"],
    credentialClass: "internal_service",
    credentialEnv: "AGENT_THINK_SERVICE_BEARER",
    callers: [{
      sourceDomain: "memory.example.com",
      serviceId: "<MEMORY_SERVICE>-think-gateway",
      evidence: "confirmed",
      sourcePath: "src/memory/think/productionAgentGatewayClient.ts",
    }],
  },
  {
    id: "agent:think:skills:search",
    deploymentTarget: "agent",
    host: "<AGENT_SERVICE>.internal",
    path: "/service/think/skills/search",
    methods: ["POST"],
    credentialClass: "internal_service",
    credentialEnv: "AGENT_THINK_SERVICE_BEARER",
    callers: [{
      sourceDomain: "memory.example.com",
      serviceId: "<MEMORY_SERVICE>-think-gateway",
      evidence: "confirmed",
      sourcePath: "src/memory/think/productionAgentGatewayClient.ts",
    }],
  },
  {
    id: "agent:think:skills:activate",
    deploymentTarget: "agent",
    host: "<AGENT_SERVICE>.internal",
    path: "/service/think/skills/activate",
    methods: ["POST"],
    credentialClass: "internal_service",
    credentialEnv: "AGENT_THINK_SERVICE_BEARER",
    callers: [{
      sourceDomain: "memory.example.com",
      serviceId: "<MEMORY_SERVICE>-think-gateway",
      evidence: "confirmed",
      sourcePath: "src/memory/think/productionAgentGatewayClient.ts",
    }],
  },
  {
    id: "agent:operia:dashboard",
    deploymentTarget: "agent",
    host: "<AGENT_SERVICE>.internal",
    path: "/service/operia/dashboard",
    methods: ["GET"],
    credentialClass: "internal_service",
    credentialEnv: "AGENT_DASHBOARD_SERVICE_BEARER",
    callers: [{
      sourceDomain: "operia-dashboard",
      serviceId: "operia-dashboard",
      evidence: "confirmed",
      sourcePath: "src/agent/dashboardProjection.ts",
    }],
  },
  {
    id: "agent:context:handles",
    deploymentTarget: "agent",
    host: "<AGENT_SERVICE>.internal",
    path: "/service/context/handles",
    methods: ["POST"],
    credentialClass: "internal_service",
    credentialEnv: "AGENT_CONTEXT_SERVICE_BEARER",
    callers: [{
      sourceDomain: "tgbot.example.com",
      serviceId: "telegram-agent",
      evidence: "confirmed",
      sourcePath: "src/tg/agentClient.ts",
    }],
  },
  {
    id: "agent:context:capsules",
    deploymentTarget: "agent",
    host: "<AGENT_SERVICE>.internal",
    path: "/service/context/capsules",
    methods: ["POST"],
    credentialClass: "internal_service",
    credentialEnv: "AGENT_CONTEXT_SERVICE_BEARER",
    callers: [{
      sourceDomain: "tgbot.example.com",
      serviceId: "telegram-agent",
      evidence: "confirmed",
      sourcePath: "src/tg/agentClient.ts",
    }],
  },
  {
    id: "agent:context:resolve",
    deploymentTarget: "agent",
    host: "<AGENT_SERVICE>.internal",
    path: "/service/context/resolve",
    methods: ["POST"],
    credentialClass: "internal_service",
    credentialEnv: "AGENT_CONTEXT_SERVICE_BEARER",
    callers: [{
      sourceDomain: "tgbot.example.com",
      serviceId: "telegram-agent",
      evidence: "confirmed",
      sourcePath: "src/tg/agentClient.ts",
    }],
  },
  {
    id: "agent:catalog:refresh",
    deploymentTarget: "agent",
    host: "<AGENT_SERVICE>.internal",
    path: "/service/catalog/refresh",
    methods: ["POST"],
    credentialClass: "internal_service",
    credentialEnv: "AGENT_CONTEXT_SERVICE_BEARER",
    callers: [{
      sourceDomain: "tgbot.example.com",
      serviceId: "telegram-agent",
      evidence: "confirmed",
      sourcePath: "src/tg/agentClient.ts",
    }],
  },
  {
    id: "agent:policy:evaluate",
    deploymentTarget: "agent",
    host: "<AGENT_SERVICE>.internal",
    path: "/service/policy/evaluate",
    methods: ["POST"],
    credentialClass: "internal_service",
    credentialEnv: "AGENT_CONTEXT_SERVICE_BEARER",
    callers: [{
      sourceDomain: "tgbot.example.com",
      serviceId: "telegram-agent",
      evidence: "confirmed",
      sourcePath: "src/tg/agentClient.ts",
    }],
  },
  {
    id: "agent:policy:sanitize",
    deploymentTarget: "agent",
    host: "<AGENT_SERVICE>.internal",
    path: "/service/policy/sanitize",
    methods: ["POST"],
    credentialClass: "internal_service",
    credentialEnv: "AGENT_CONTEXT_SERVICE_BEARER",
    callers: [{
      sourceDomain: "tgbot.example.com",
      serviceId: "telegram-agent",
      evidence: "confirmed",
      sourcePath: "src/tg/agentClient.ts",
    }],
  },
  {
    id: "agent:runtime:snapshot",
    deploymentTarget: "agent",
    host: "<AGENT_SERVICE>.internal",
    path: "/service/runtime/snapshot",
    methods: ["GET"],
    credentialClass: "internal_service",
    credentialEnv: "AGENT_CONTEXT_SERVICE_BEARER",
    callers: [{
      sourceDomain: "tgbot.example.com",
      serviceId: "telegram-agent",
      evidence: "confirmed",
      sourcePath: "src/tg/agentClient.ts",
    }],
  },
  {
    id: "agent:operations:projection",
    deploymentTarget: "agent",
    host: "<AGENT_SERVICE>.internal",
    path: "/service/operations/projection",
    methods: ["GET"],
    credentialClass: "internal_service",
    credentialEnv: "AGENT_CONTEXT_SERVICE_BEARER",
    callers: [{
      sourceDomain: "tgbot.example.com",
      serviceId: "telegram-agent",
      evidence: "confirmed",
      sourcePath: "src/tg/agentClient.ts",
    }],
  },
  {
    id: "agent:runtime:trace",
    deploymentTarget: "agent",
    host: "<AGENT_SERVICE>.internal",
    path: "/service/runtime/trace",
    methods: ["GET"],
    credentialClass: "internal_service",
    credentialEnv: "AGENT_CONTEXT_SERVICE_BEARER",
    callers: [{
      sourceDomain: "tgbot.example.com",
      serviceId: "telegram-agent",
      evidence: "confirmed",
      sourcePath: "src/tg/agentClient.ts",
    }],
  },
  {
    id: "agent:control:projection",
    deploymentTarget: "agent",
    host: "<AGENT_SERVICE>.internal",
    path: "/service/control/projection",
    methods: ["GET"],
    credentialClass: "internal_service",
    credentialEnv: "AGENT_CONTEXT_SERVICE_BEARER",
    callers: [{
      sourceDomain: "tgbot.example.com",
      serviceId: "telegram-agent",
      evidence: "confirmed",
      sourcePath: "src/tg/agentClient.ts",
    }],
  },
  {
    id: "agent:heartbeat:projection",
    deploymentTarget: "agent",
    host: "<AGENT_SERVICE>.internal",
    path: "/service/heartbeat/projection",
    methods: ["GET"],
    credentialClass: "internal_service",
    credentialEnv: "AGENT_CONTEXT_SERVICE_BEARER",
    callers: [{
      sourceDomain: "tgbot.example.com",
      serviceId: "telegram-agent",
      evidence: "confirmed",
      sourcePath: "src/tg/agentClient.ts",
    }],
  },
  {
    id: "agent:heartbeat:config",
    deploymentTarget: "agent",
    host: "<AGENT_SERVICE>.internal",
    path: "/service/heartbeat/config",
    methods: ["PUT"],
    credentialClass: "internal_service",
    credentialEnv: "AGENT_CONTEXT_SERVICE_BEARER",
    callers: [{
      sourceDomain: "tgbot.example.com",
      serviceId: "telegram-agent",
      evidence: "confirmed",
      sourcePath: "src/tg/agentClient.ts",
    }],
  },
  {
    id: "agent:heartbeat:activity",
    deploymentTarget: "agent",
    host: "<AGENT_SERVICE>.internal",
    path: "/service/heartbeat/activity",
    methods: ["POST"],
    credentialClass: "internal_service",
    credentialEnv: "AGENT_CONTEXT_SERVICE_BEARER",
    callers: [{
      sourceDomain: "tgbot.example.com",
      serviceId: "telegram-agent",
      evidence: "confirmed",
      sourcePath: "src/tg/agentClient.ts",
    }],
  },
  {
    id: "agent:heartbeat:activation:decision",
    deploymentTarget: "agent",
    host: "<AGENT_SERVICE>.internal",
    path: "/service/heartbeat/activation/:id/decision",
    methods: ["POST"],
    credentialClass: "internal_service",
    credentialEnv: "AGENT_CONTEXT_SERVICE_BEARER",
    callers: [{
      sourceDomain: "tgbot.example.com",
      serviceId: "telegram-agent",
      evidence: "confirmed",
      sourcePath: "src/tg/agentClient.ts",
    }],
  },
  {
    id: "agent:heartbeat:intents:claim",
    deploymentTarget: "agent",
    host: "<AGENT_SERVICE>.internal",
    path: "/service/heartbeat/intents/claim",
    methods: ["POST"],
    credentialClass: "internal_service",
    credentialEnv: "AGENT_CONTEXT_SERVICE_BEARER",
    callers: [{
      sourceDomain: "tgbot.example.com",
      serviceId: "telegram-agent",
      evidence: "confirmed",
      sourcePath: "src/tg/agentClient.ts",
    }],
  },
  {
    id: "agent:heartbeat:intents:complete",
    deploymentTarget: "agent",
    host: "<AGENT_SERVICE>.internal",
    path: "/service/heartbeat/intents/:id/complete",
    methods: ["POST"],
    credentialClass: "internal_service",
    credentialEnv: "AGENT_CONTEXT_SERVICE_BEARER",
    callers: [{
      sourceDomain: "tgbot.example.com",
      serviceId: "telegram-agent",
      evidence: "confirmed",
      sourcePath: "src/tg/agentClient.ts",
    }],
  },
  {
    id: "agent:heartbeat:intents:fail",
    deploymentTarget: "agent",
    host: "<AGENT_SERVICE>.internal",
    path: "/service/heartbeat/intents/:id/fail",
    methods: ["POST"],
    credentialClass: "internal_service",
    credentialEnv: "AGENT_CONTEXT_SERVICE_BEARER",
    callers: [{
      sourceDomain: "tgbot.example.com",
      serviceId: "telegram-agent",
      evidence: "confirmed",
      sourcePath: "src/tg/agentClient.ts",
    }],
  },
  {
    id: "agent:mcp:control",
    deploymentTarget: "agent",
    host: "<AGENT_SERVICE>.internal",
    path: "/service/mcp/control",
    methods: ["GET"],
    credentialClass: "internal_service",
    credentialEnv: "AGENT_CONTEXT_SERVICE_BEARER",
    callers: [{
      sourceDomain: "tgbot.example.com",
      serviceId: "telegram-agent",
      evidence: "confirmed",
      sourcePath: "src/tg/agentClient.ts",
    }],
  },
  {
    id: "agent:artifacts",
    deploymentTarget: "agent",
    host: "<AGENT_SERVICE>.internal",
    path: "/service/artifacts",
    methods: ["GET"],
    credentialClass: "internal_service",
    credentialEnv: "AGENT_CONTEXT_SERVICE_BEARER",
    callers: [{
      sourceDomain: "tgbot.example.com",
      serviceId: "telegram-agent",
      evidence: "confirmed",
      sourcePath: "src/tg/agentClient.ts",
    }],
  },
  {
    id: "agent:sandbox:control",
    deploymentTarget: "agent",
    host: "<AGENT_SERVICE>.internal",
    path: "/service/sandbox/control",
    methods: ["POST"],
    credentialClass: "internal_service",
    credentialEnv: "AGENT_CONTEXT_SERVICE_BEARER",
    callers: [{
      sourceDomain: "tgbot.example.com",
      serviceId: "telegram-agent",
      evidence: "confirmed",
      sourcePath: "src/tg/agentClient.ts",
    }],
  },
  {
    id: "agent:sandbox:connector",
    deploymentTarget: "agent",
    host: "<AGENT_SERVICE>.internal",
    path: "/service/sandbox/connector",
    methods: ["POST"],
    credentialClass: "internal_service",
    credentialEnv: "AGENT_CONTEXT_SERVICE_BEARER",
    callers: [{
      sourceDomain: "tgbot.example.com",
      serviceId: "telegram-agent",
      evidence: "confirmed",
      sourcePath: "src/tg/agentClient.ts",
    }],
  },
  {
    id: "agent:mcp:tools",
    deploymentTarget: "agent",
    host: "<AGENT_SERVICE>.internal",
    path: "/service/mcp/tools",
    methods: ["PATCH"],
    credentialClass: "internal_service",
    credentialEnv: "AGENT_CONTEXT_SERVICE_BEARER",
    callers: [{
      sourceDomain: "tgbot.example.com",
      serviceId: "telegram-agent",
      evidence: "confirmed",
      sourcePath: "src/tg/agentClient.ts",
    }],
  },
  {
    id: "agent:telegram:tool",
    deploymentTarget: "agent",
    host: "<AGENT_SERVICE>.internal",
    path: "/service/telegram/tool",
    methods: ["POST"],
    credentialClass: "internal_service",
    credentialEnv: "AGENT_CONTEXT_SERVICE_BEARER",
    callers: [{
      sourceDomain: "tgbot.example.com",
      serviceId: "telegram-agent",
      evidence: "confirmed",
      sourcePath: "src/tg/agentClient.ts",
    }],
  },
  {
    id: "agent:telegram:skill",
    deploymentTarget: "agent",
    host: "<AGENT_SERVICE>.internal",
    path: "/service/telegram/skill",
    methods: ["POST"],
    credentialClass: "internal_service",
    credentialEnv: "AGENT_CONTEXT_SERVICE_BEARER",
    callers: [{
      sourceDomain: "tgbot.example.com",
      serviceId: "telegram-agent",
      evidence: "confirmed",
      sourcePath: "src/tg/agentClient.ts",
    }],
  },
  {
    id: "agent:telegram:browser",
    deploymentTarget: "agent",
    host: "<AGENT_SERVICE>.internal",
    path: "/service/telegram/browser",
    methods: ["POST"],
    credentialClass: "internal_service",
    credentialEnv: "AGENT_CONTEXT_SERVICE_BEARER",
    callers: [{
      sourceDomain: "tgbot.example.com",
      serviceId: "telegram-agent",
      evidence: "confirmed",
      sourcePath: "src/tg/agentClient.ts",
    }],
  },
  {
    id: "agent:tasks",
    deploymentTarget: "agent",
    host: "<AGENT_SERVICE>.internal",
    path: "/service/tasks",
    methods: ["POST"],
    credentialClass: "internal_service",
    credentialEnv: "AGENT_CONTEXT_SERVICE_BEARER",
    callers: [{
      sourceDomain: "tgbot.example.com",
      serviceId: "telegram-agent",
      evidence: "confirmed",
      sourcePath: "src/tg/agentClient.ts",
    }],
  },
  {
    id: "agent:tasks:direct",
    deploymentTarget: "agent",
    host: "<AGENT_SERVICE>.internal",
    path: "/service/tasks/direct",
    methods: ["POST"],
    credentialClass: "internal_service",
    credentialEnv: "AGENT_CONTEXT_SERVICE_BEARER",
    callers: [{
      sourceDomain: "tgbot.example.com",
      serviceId: "telegram-agent",
      evidence: "confirmed",
      sourcePath: "src/tg/agentClient.ts",
    }],
  },
  {
    id: "agent:providers:voice:transcribe",
    deploymentTarget: "agent",
    host: "<AGENT_SERVICE>.internal",
    path: "/service/providers/voice/transcribe",
    methods: ["POST"],
    credentialClass: "internal_service",
    credentialEnv: "AGENT_CONTEXT_SERVICE_BEARER",
    callers: [{
      sourceDomain: "tgbot.example.com",
      serviceId: "telegram-agent",
      evidence: "confirmed",
      sourcePath: "src/tg/agentClient.ts",
    }],
  },
  {
    id: "agent:providers:voice:synthesize",
    deploymentTarget: "agent",
    host: "<AGENT_SERVICE>.internal",
    path: "/service/providers/voice/synthesize",
    methods: ["POST"],
    credentialClass: "internal_service",
    credentialEnv: "AGENT_CONTEXT_SERVICE_BEARER",
    callers: [{
      sourceDomain: "tgbot.example.com",
      serviceId: "telegram-agent",
      evidence: "confirmed",
      sourcePath: "src/tg/agentClient.ts",
    }],
  },
  {
    id: "agent:presentation:music-poster",
    deploymentTarget: "agent",
    host: "<AGENT_SERVICE>.internal",
    path: "/service/presentation/music-poster",
    methods: ["POST"],
    credentialClass: "internal_service",
    credentialEnv: "AGENT_CONTEXT_SERVICE_BEARER",
    callers: [{
      sourceDomain: "tgbot.example.com",
      serviceId: "telegram-agent",
      evidence: "confirmed",
      sourcePath: "src/tg/agentClient.ts",
    }],
  },
  {
    id: "agent:approvals:prepare",
    deploymentTarget: "agent",
    host: "<AGENT_SERVICE>.internal",
    path: "/service/approvals/prepare",
    methods: ["POST"],
    credentialClass: "internal_service",
    credentialEnv: "AGENT_APPROVAL_SERVICE_BEARER",
    callers: [{
      sourceDomain: "tgbot.example.com",
      serviceId: "telegram-agent",
      evidence: "confirmed",
      sourcePath: "src/tg/agentClient.ts",
    }],
  },
  {
    id: "agent:approvals:decide",
    deploymentTarget: "agent",
    host: "<AGENT_SERVICE>.internal",
    path: "/service/approvals/:ticketId/decide",
    methods: ["POST"],
    credentialClass: "internal_service",
    credentialEnv: "AGENT_APPROVAL_SERVICE_BEARER",
    callers: [{
      sourceDomain: "tgbot.example.com",
      serviceId: "telegram-agent",
      evidence: "confirmed",
      sourcePath: "src/tg/agentClient.ts",
    }],
  },
  {
    id: "agent:browser:domain-challenges",
    deploymentTarget: "agent",
    host: "<AGENT_SERVICE>.internal",
    path: "/service/browser/domain-challenges/*",
    methods: ["GET", "POST", "PUT", "DELETE"],
    credentialClass: "internal_service",
    credentialEnv: "AGENT_APPROVAL_SERVICE_BEARER",
    callers: [{
      sourceDomain: "tgbot.example.com",
      serviceId: "telegram-agent",
      evidence: "confirmed",
      sourcePath: "src/tg/agentClient.ts",
    }],
  },
  {
    id: "agent:grok:v1:responses",
    deploymentTarget: "agent",
    host: "<AGENT_SERVICE>.internal",
    path: "/service/agent/grok/v1/responses",
    methods: ["POST"],
    credentialClass: "internal_service",
    credentialEnv: "AGENT_GATEWAY_BROKER_API_KEY",
    callers: [{
      sourceDomain: "agent.example.com",
      serviceId: "agent-grok-gateway-broker",
      evidence: "confirmed",
      sourcePath: "src/api/agentGatewayBroker.ts",
    }],
  },
  {
    id: "agent:grok:v1:images:generations",
    deploymentTarget: "agent",
    host: "<AGENT_SERVICE>.internal",
    path: "/service/agent/grok/v1/images/generations",
    methods: ["POST"],
    credentialClass: "internal_service",
    credentialEnv: "AGENT_GATEWAY_BROKER_API_KEY",
    callers: [{
      sourceDomain: "agent.example.com",
      serviceId: "agent-grok-gateway-broker",
      evidence: "confirmed",
      sourcePath: "src/api/agentGatewayBroker.ts",
    }],
  },
  {
    id: "agent:grok:v1:images:edits",
    deploymentTarget: "agent",
    host: "<AGENT_SERVICE>.internal",
    path: "/service/agent/grok/v1/images/edits",
    methods: ["POST"],
    credentialClass: "internal_service",
    credentialEnv: "AGENT_GATEWAY_BROKER_API_KEY",
    callers: [{
      sourceDomain: "agent.example.com",
      serviceId: "agent-grok-gateway-broker",
      evidence: "confirmed",
      sourcePath: "src/api/agentGatewayBroker.ts",
    }],
  },

  // ---------------------------------------------------------------------------
  // Think Gate-D canary worker
  // ---------------------------------------------------------------------------
  {
    id: "think-gate-d:think:catalog",
    deploymentTarget: "think-gate-d-canary",
    host: "<AGENT_SERVICE>.internal",
    path: "/service/think/catalog",
    methods: ["GET"],
    credentialClass: "internal_service",
    credentialEnv: "THINK_GATE_D_CANARY_BEARER",
    callers: [{
      sourceDomain: "memory.example.com",
      serviceId: "<MEMORY_SERVICE>-think-gateway",
      evidence: "confirmed",
      sourcePath: "src/memory/think/productionAgentGatewayClient.ts",
    }],
  },
  {
    id: "think-gate-d:think:describe",
    deploymentTarget: "think-gate-d-canary",
    host: "<AGENT_SERVICE>.internal",
    path: "/service/think/describe",
    methods: ["POST"],
    credentialClass: "internal_service",
    credentialEnv: "THINK_GATE_D_CANARY_BEARER",
    callers: [{
      sourceDomain: "memory.example.com",
      serviceId: "<MEMORY_SERVICE>-think-gateway",
      evidence: "confirmed",
      sourcePath: "src/memory/think/productionAgentGatewayClient.ts",
    }],
  },
  {
    id: "think-gate-d:think:execute",
    deploymentTarget: "think-gate-d-canary",
    host: "<AGENT_SERVICE>.internal",
    path: "/service/think/execute",
    methods: ["POST"],
    credentialClass: "internal_service",
    credentialEnv: "THINK_GATE_D_CANARY_BEARER",
    callers: [{
      sourceDomain: "memory.example.com",
      serviceId: "<MEMORY_SERVICE>-think-gateway",
      evidence: "confirmed",
      sourcePath: "src/memory/think/productionAgentGatewayClient.ts",
    }],
  },
];

/**
 * Registry helpers used by H-C1 enforcement and tests.
 */

export function internalServiceRouteKey(route: InternalServiceRoute): string {
  return [route.deploymentTarget, route.host, route.path, route.methods.join(",")].join("|");
}

export function findInternalServiceRoutesByPrefix(
  routes: InternalServiceRoute[],
  host: string,
  pathnamePrefix: string,
): InternalServiceRoute[] {
  return routes.filter((route) => route.host === host && route.path.startsWith(pathnamePrefix));
}

export function findMemoryControlRoutes(routes: InternalServiceRoute[] = INTERNAL_SERVICE_ROUTES): InternalServiceRoute[] {
  return routes.filter(
    (route) =>
      route.deploymentTarget === "memory" &&
      route.credentialClass === "internal_service" &&
      route.credentialEnv === "MEMORY_CONTROL_SERVICE_BEARER" &&
      route.path.startsWith("/service/control/"),
  );
}

export function getConfirmedCallers(route: InternalServiceRoute): InternalServiceCaller[] {
  return route.callers.filter((caller) => caller.evidence === "confirmed");
}
